// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"

	"go.mondoo.com/mql/v13/llx"
	"go.mondoo.com/mql/v13/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/v13/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourceJamf                 string = "jamf"
	ResourceJamfUserByName       string = "jamf.userByName"
	ResourceComputerGroups       string = "computerGroups"
	ResourceJamfComputer         string = "jamfComputer"
	ResourceJamfLocalUserAccount string = "jamfLocalUserAccount"
	ResourceSsoSettings          string = "ssoSettings"
	ResourceJamfUsers            string = "jamfUsers"
	ResourceJamfPackages         string = "jamfPackages"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"jamf": {
			// to override args, implement: initJamf(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJamf,
		},
		"jamf.userByName": {
			Init:   initJamfUserByName,
			Create: createJamfUserByName,
		},
		"computerGroups": {
			// to override args, implement: initComputerGroups(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createComputerGroups,
		},
		"jamfComputer": {
			// to override args, implement: initJamfComputer(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJamfComputer,
		},
		"jamfLocalUserAccount": {
			// to override args, implement: initJamfLocalUserAccount(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJamfLocalUserAccount,
		},
		"ssoSettings": {
			// to override args, implement: initSsoSettings(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createSsoSettings,
		},
		"jamfUsers": {
			// to override args, implement: initJamfUsers(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJamfUsers,
		},
		"jamfPackages": {
			// to override args, implement: initJamfPackages(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createJamfPackages,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"jamf.computerInventory": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamf).GetComputerInventory()).ToDataRes(types.Array(types.Resource("jamfComputer")))
	},
	"jamf.computerInventoryCount": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamf).GetComputerInventoryCount()).ToDataRes(types.Int)
	},
	"jamf.packages": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamf).GetPackages()).ToDataRes(types.Array(types.Resource("jamfPackages")))
	},
	"jamf.sso": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamf).GetSso()).ToDataRes(types.Resource("ssoSettings"))
	},
	"jamf.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamf).GetVersion()).ToDataRes(types.String)
	},
	"jamf.users": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamf).GetUsers()).ToDataRes(types.Array(types.Resource("jamfUsers")))
	},
	"jamf.smartGroups": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamf).GetSmartGroups()).ToDataRes(types.Array(types.Resource("computerGroups")))
	},
	"jamf.userByName.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUserByName).GetId()).ToDataRes(types.Int)
	},
	"jamf.userByName.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUserByName).GetName()).ToDataRes(types.String)
	},
	"jamf.userByName.fullName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUserByName).GetFullName()).ToDataRes(types.String)
	},
	"jamf.userByName.email": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUserByName).GetEmail()).ToDataRes(types.String)
	},
	"jamf.userByName.phone": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUserByName).GetPhone()).ToDataRes(types.String)
	},
	"jamf.userByName.position": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUserByName).GetPosition()).ToDataRes(types.String)
	},
	"jamf.userByName.enableCustomPhoto": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUserByName).GetEnableCustomPhoto()).ToDataRes(types.Bool)
	},
	"computerGroups.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlComputerGroups).GetId()).ToDataRes(types.Int)
	},
	"computerGroups.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlComputerGroups).GetName()).ToDataRes(types.String)
	},
	"computerGroups.smartGroup": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlComputerGroups).GetSmartGroup()).ToDataRes(types.Bool)
	},
	"jamfComputer.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetId()).ToDataRes(types.String)
	},
	"jamfComputer.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetName()).ToDataRes(types.String)
	},
	"jamfComputer.make": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetMake()).ToDataRes(types.String)
	},
	"jamfComputer.model": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetModel()).ToDataRes(types.String)
	},
	"jamfComputer.operatingSystemName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetOperatingSystemName()).ToDataRes(types.String)
	},
	"jamfComputer.operatingSystemVersion": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetOperatingSystemVersion()).ToDataRes(types.String)
	},
	"jamfComputer.macAddress": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetMacAddress()).ToDataRes(types.String)
	},
	"jamfComputer.serialNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetSerialNumber()).ToDataRes(types.String)
	},
	"jamfComputer.processorType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetProcessorType()).ToDataRes(types.String)
	},
	"jamfComputer.processorCount": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetProcessorCount()).ToDataRes(types.Int)
	},
	"jamfComputer.coreCount": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetCoreCount()).ToDataRes(types.Int)
	},
	"jamfComputer.totalRamMegabytes": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetTotalRamMegabytes()).ToDataRes(types.Int)
	},
	"jamfComputer.lastIpAddress": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetLastIpAddress()).ToDataRes(types.String)
	},
	"jamfComputer.lastReportedIp": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetLastReportedIp()).ToDataRes(types.String)
	},
	"jamfComputer.jamfBinaryVersion": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetJamfBinaryVersion()).ToDataRes(types.String)
	},
	"jamfComputer.platform": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetPlatform()).ToDataRes(types.String)
	},
	"jamfComputer.reportDate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetReportDate()).ToDataRes(types.String)
	},
	"jamfComputer.lastContactTime": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetLastContactTime()).ToDataRes(types.String)
	},
	"jamfComputer.lastEnrolledDate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetLastEnrolledDate()).ToDataRes(types.String)
	},
	"jamfComputer.initialEntryDate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetInitialEntryDate()).ToDataRes(types.String)
	},
	"jamfComputer.itunesStoreAccountActive": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetItunesStoreAccountActive()).ToDataRes(types.Bool)
	},
	"jamfComputer.enrolledViaAutomatedDeviceEnrollment": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetEnrolledViaAutomatedDeviceEnrollment()).ToDataRes(types.Bool)
	},
	"jamfComputer.fileVault2Enabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetFileVault2Enabled()).ToDataRes(types.String)
	},
	"jamfComputer.autoLoginDisabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetAutoLoginDisabled()).ToDataRes(types.Bool)
	},
	"jamfComputer.activationLockEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetActivationLockEnabled()).ToDataRes(types.Bool)
	},
	"jamfComputer.firewallEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetFirewallEnabled()).ToDataRes(types.Bool)
	},
	"jamfComputer.localUserAccounts": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfComputer).GetLocalUserAccounts()).ToDataRes(types.Array(types.Resource("jamfLocalUserAccount")))
	},
	"jamfLocalUserAccount.uid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetUid()).ToDataRes(types.String)
	},
	"jamfLocalUserAccount.username": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetUsername()).ToDataRes(types.String)
	},
	"jamfLocalUserAccount.fullName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetFullName()).ToDataRes(types.String)
	},
	"jamfLocalUserAccount.admin": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetAdmin()).ToDataRes(types.Bool)
	},
	"jamfLocalUserAccount.fileVault2Enabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetFileVault2Enabled()).ToDataRes(types.Bool)
	},
	"jamfLocalUserAccount.userAccountType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetUserAccountType()).ToDataRes(types.String)
	},
	"jamfLocalUserAccount.passwordMaxAge": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetPasswordMaxAge()).ToDataRes(types.Int)
	},
	"jamfLocalUserAccount.homeDirectory": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetHomeDirectory()).ToDataRes(types.String)
	},
	"jamfLocalUserAccount.passwordMinLength": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetPasswordMinLength()).ToDataRes(types.Int)
	},
	"jamfLocalUserAccount.passwordMinComplexCharacters": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfLocalUserAccount).GetPasswordMinComplexCharacters()).ToDataRes(types.Int)
	},
	"ssoSettings.ssoEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetSsoEnabled()).ToDataRes(types.Bool)
	},
	"ssoSettings.ssoForEnrollmentEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetSsoForEnrollmentEnabled()).ToDataRes(types.Bool)
	},
	"ssoSettings.ssoBypassAllowed": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetSsoBypassAllowed()).ToDataRes(types.Bool)
	},
	"ssoSettings.sessionTimeout": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetSessionTimeout()).ToDataRes(types.Int)
	},
	"ssoSettings.ssoForMacOsSelfServiceEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetSsoForMacOsSelfServiceEnabled()).ToDataRes(types.Bool)
	},
	"ssoSettings.tokenExpirationDisabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetTokenExpirationDisabled()).ToDataRes(types.Bool)
	},
	"ssoSettings.userAttributeEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetUserAttributeEnabled()).ToDataRes(types.Bool)
	},
	"ssoSettings.userAttributeName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetUserAttributeName()).ToDataRes(types.String)
	},
	"ssoSettings.userMapping": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetUserMapping()).ToDataRes(types.String)
	},
	"ssoSettings.enrollmentSsoForAccountDrivenEnrollmentEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetEnrollmentSsoForAccountDrivenEnrollmentEnabled()).ToDataRes(types.Bool)
	},
	"ssoSettings.idpUrl": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetIdpUrl()).ToDataRes(types.String)
	},
	"ssoSettings.idpProviderType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetIdpProviderType()).ToDataRes(types.String)
	},
	"ssoSettings.groupEnrollmentAccessEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetGroupEnrollmentAccessEnabled()).ToDataRes(types.Bool)
	},
	"ssoSettings.groupAttributeName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetGroupAttributeName()).ToDataRes(types.String)
	},
	"ssoSettings.entityId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlSsoSettings).GetEntityId()).ToDataRes(types.String)
	},
	"jamfUsers.id": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUsers).GetId()).ToDataRes(types.Int)
	},
	"jamfUsers.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfUsers).GetName()).ToDataRes(types.String)
	},
	"jamfPackages.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfPackages).GetName()).ToDataRes(types.String)
	},
	"jamfPackages.fileName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfPackages).GetFileName()).ToDataRes(types.String)
	},
	"jamfPackages.oSInstall": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfPackages).GetOSInstall()).ToDataRes(types.Bool)
	},
	"jamfPackages.categoryId": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfPackages).GetCategoryId()).ToDataRes(types.String)
	},
	"jamfPackages.priority": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfPackages).GetPriority()).ToDataRes(types.Int)
	},
	"jamfPackages.suppressUpdates": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfPackages).GetSuppressUpdates()).ToDataRes(types.Bool)
	},
	"jamfPackages.suppressRegistration": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlJamfPackages).GetSuppressRegistration()).ToDataRes(types.Bool)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"jamf.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).__id, ok = v.Value.(string)
		return
	},
	"jamf.computerInventory": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).ComputerInventory, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jamf.computerInventoryCount": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).ComputerInventoryCount, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamf.packages": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).Packages, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jamf.sso": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).Sso, ok = plugin.RawToTValue[*mqlSsoSettings](v.Value, v.Error)
		return
	},
	"jamf.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamf.users": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).Users, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jamf.smartGroups": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamf).SmartGroups, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jamf.userByName.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).__id, ok = v.Value.(string)
		return
	},
	"jamf.userByName.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).Id, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamf.userByName.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamf.userByName.fullName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).FullName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamf.userByName.email": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).Email, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamf.userByName.phone": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).Phone, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamf.userByName.position": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).Position, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamf.userByName.enableCustomPhoto": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUserByName).EnableCustomPhoto, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"computerGroups.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlComputerGroups).__id, ok = v.Value.(string)
		return
	},
	"computerGroups.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlComputerGroups).Id, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"computerGroups.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlComputerGroups).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"computerGroups.smartGroup": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlComputerGroups).SmartGroup, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfComputer.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).__id, ok = v.Value.(string)
		return
	},
	"jamfComputer.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).Id, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.make": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).Make, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.model": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).Model, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.operatingSystemName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).OperatingSystemName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.operatingSystemVersion": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).OperatingSystemVersion, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.macAddress": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).MacAddress, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.serialNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).SerialNumber, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.processorType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).ProcessorType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.processorCount": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).ProcessorCount, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamfComputer.coreCount": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).CoreCount, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamfComputer.totalRamMegabytes": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).TotalRamMegabytes, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamfComputer.lastIpAddress": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).LastIpAddress, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.lastReportedIp": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).LastReportedIp, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.jamfBinaryVersion": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).JamfBinaryVersion, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.platform": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).Platform, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.reportDate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).ReportDate, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.lastContactTime": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).LastContactTime, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.lastEnrolledDate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).LastEnrolledDate, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.initialEntryDate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).InitialEntryDate, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.itunesStoreAccountActive": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).ItunesStoreAccountActive, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfComputer.enrolledViaAutomatedDeviceEnrollment": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).EnrolledViaAutomatedDeviceEnrollment, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfComputer.fileVault2Enabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).FileVault2Enabled, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfComputer.autoLoginDisabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).AutoLoginDisabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfComputer.activationLockEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).ActivationLockEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfComputer.firewallEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).FirewallEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfComputer.localUserAccounts": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfComputer).LocalUserAccounts, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).__id, ok = v.Value.(string)
		return
	},
	"jamfLocalUserAccount.uid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).Uid, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.username": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).Username, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.fullName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).FullName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.admin": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).Admin, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.fileVault2Enabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).FileVault2Enabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.userAccountType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).UserAccountType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.passwordMaxAge": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).PasswordMaxAge, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.homeDirectory": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).HomeDirectory, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.passwordMinLength": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).PasswordMinLength, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamfLocalUserAccount.passwordMinComplexCharacters": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfLocalUserAccount).PasswordMinComplexCharacters, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"ssoSettings.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).__id, ok = v.Value.(string)
		return
	},
	"ssoSettings.ssoEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).SsoEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.ssoForEnrollmentEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).SsoForEnrollmentEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.ssoBypassAllowed": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).SsoBypassAllowed, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.sessionTimeout": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).SessionTimeout, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"ssoSettings.ssoForMacOsSelfServiceEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).SsoForMacOsSelfServiceEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.tokenExpirationDisabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).TokenExpirationDisabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.userAttributeEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).UserAttributeEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.userAttributeName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).UserAttributeName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"ssoSettings.userMapping": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).UserMapping, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"ssoSettings.enrollmentSsoForAccountDrivenEnrollmentEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).EnrollmentSsoForAccountDrivenEnrollmentEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.idpUrl": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).IdpUrl, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"ssoSettings.idpProviderType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).IdpProviderType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"ssoSettings.groupEnrollmentAccessEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).GroupEnrollmentAccessEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"ssoSettings.groupAttributeName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).GroupAttributeName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"ssoSettings.entityId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlSsoSettings).EntityId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfUsers.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUsers).__id, ok = v.Value.(string)
		return
	},
	"jamfUsers.id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUsers).Id, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamfUsers.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfUsers).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfPackages.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).__id, ok = v.Value.(string)
		return
	},
	"jamfPackages.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfPackages.fileName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).FileName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfPackages.oSInstall": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).OSInstall, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfPackages.categoryId": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).CategoryId, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"jamfPackages.priority": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).Priority, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"jamfPackages.suppressUpdates": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).SuppressUpdates, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"jamfPackages.suppressRegistration": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlJamfPackages).SuppressRegistration, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[jamf] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[jamf] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlJamf for the jamf resource
type mqlJamf struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJamfInternal it will be used here
	ComputerInventory      plugin.TValue[[]any]
	ComputerInventoryCount plugin.TValue[int64]
	Packages               plugin.TValue[[]any]
	Sso                    plugin.TValue[*mqlSsoSettings]
	Version                plugin.TValue[string]
	Users                  plugin.TValue[[]any]
	SmartGroups            plugin.TValue[[]any]
}

// createJamf creates a new instance of this resource
func createJamf(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJamf{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jamf", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJamf) MqlName() string {
	return "jamf"
}

func (c *mqlJamf) MqlID() string {
	return c.__id
}

func (c *mqlJamf) GetComputerInventory() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.ComputerInventory, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jamf", c.__id, "computerInventory")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.computerInventory()
	})
}

func (c *mqlJamf) GetComputerInventoryCount() *plugin.TValue[int64] {
	return plugin.GetOrCompute[int64](&c.ComputerInventoryCount, func() (int64, error) {
		return c.computerInventoryCount()
	})
}

func (c *mqlJamf) GetPackages() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Packages, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jamf", c.__id, "packages")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.packages()
	})
}

func (c *mqlJamf) GetSso() *plugin.TValue[*mqlSsoSettings] {
	return plugin.GetOrCompute[*mqlSsoSettings](&c.Sso, func() (*mqlSsoSettings, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jamf", c.__id, "sso")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.(*mqlSsoSettings), nil
			}
		}

		return c.sso()
	})
}

func (c *mqlJamf) GetVersion() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.Version, func() (string, error) {
		return c.version()
	})
}

func (c *mqlJamf) GetUsers() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Users, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jamf", c.__id, "users")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.users()
	})
}

func (c *mqlJamf) GetSmartGroups() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.SmartGroups, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jamf", c.__id, "smartGroups")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.smartGroups()
	})
}

// mqlJamfUserByName for the jamf.userByName resource
type mqlJamfUserByName struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJamfUserByNameInternal it will be used here
	Id                plugin.TValue[int64]
	Name              plugin.TValue[string]
	FullName          plugin.TValue[string]
	Email             plugin.TValue[string]
	Phone             plugin.TValue[string]
	Position          plugin.TValue[string]
	EnableCustomPhoto plugin.TValue[bool]
}

// createJamfUserByName creates a new instance of this resource
func createJamfUserByName(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJamfUserByName{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jamf.userByName", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJamfUserByName) MqlName() string {
	return "jamf.userByName"
}

func (c *mqlJamfUserByName) MqlID() string {
	return c.__id
}

func (c *mqlJamfUserByName) GetId() *plugin.TValue[int64] {
	return &c.Id
}

func (c *mqlJamfUserByName) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlJamfUserByName) GetFullName() *plugin.TValue[string] {
	return &c.FullName
}

func (c *mqlJamfUserByName) GetEmail() *plugin.TValue[string] {
	return &c.Email
}

func (c *mqlJamfUserByName) GetPhone() *plugin.TValue[string] {
	return &c.Phone
}

func (c *mqlJamfUserByName) GetPosition() *plugin.TValue[string] {
	return &c.Position
}

func (c *mqlJamfUserByName) GetEnableCustomPhoto() *plugin.TValue[bool] {
	return &c.EnableCustomPhoto
}

// mqlComputerGroups for the computerGroups resource
type mqlComputerGroups struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlComputerGroupsInternal it will be used here
	Id         plugin.TValue[int64]
	Name       plugin.TValue[string]
	SmartGroup plugin.TValue[bool]
}

// createComputerGroups creates a new instance of this resource
func createComputerGroups(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlComputerGroups{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("computerGroups", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlComputerGroups) MqlName() string {
	return "computerGroups"
}

func (c *mqlComputerGroups) MqlID() string {
	return c.__id
}

func (c *mqlComputerGroups) GetId() *plugin.TValue[int64] {
	return &c.Id
}

func (c *mqlComputerGroups) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlComputerGroups) GetSmartGroup() *plugin.TValue[bool] {
	return &c.SmartGroup
}

// mqlJamfComputer for the jamfComputer resource
type mqlJamfComputer struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJamfComputerInternal it will be used here
	Id                                   plugin.TValue[string]
	Name                                 plugin.TValue[string]
	Make                                 plugin.TValue[string]
	Model                                plugin.TValue[string]
	OperatingSystemName                  plugin.TValue[string]
	OperatingSystemVersion               plugin.TValue[string]
	MacAddress                           plugin.TValue[string]
	SerialNumber                         plugin.TValue[string]
	ProcessorType                        plugin.TValue[string]
	ProcessorCount                       plugin.TValue[int64]
	CoreCount                            plugin.TValue[int64]
	TotalRamMegabytes                    plugin.TValue[int64]
	LastIpAddress                        plugin.TValue[string]
	LastReportedIp                       plugin.TValue[string]
	JamfBinaryVersion                    plugin.TValue[string]
	Platform                             plugin.TValue[string]
	ReportDate                           plugin.TValue[string]
	LastContactTime                      plugin.TValue[string]
	LastEnrolledDate                     plugin.TValue[string]
	InitialEntryDate                     plugin.TValue[string]
	ItunesStoreAccountActive             plugin.TValue[bool]
	EnrolledViaAutomatedDeviceEnrollment plugin.TValue[bool]
	FileVault2Enabled                    plugin.TValue[string]
	AutoLoginDisabled                    plugin.TValue[bool]
	ActivationLockEnabled                plugin.TValue[bool]
	FirewallEnabled                      plugin.TValue[bool]
	LocalUserAccounts                    plugin.TValue[[]any]
}

// createJamfComputer creates a new instance of this resource
func createJamfComputer(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJamfComputer{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jamfComputer", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJamfComputer) MqlName() string {
	return "jamfComputer"
}

func (c *mqlJamfComputer) MqlID() string {
	return c.__id
}

func (c *mqlJamfComputer) GetId() *plugin.TValue[string] {
	return &c.Id
}

func (c *mqlJamfComputer) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlJamfComputer) GetMake() *plugin.TValue[string] {
	return &c.Make
}

func (c *mqlJamfComputer) GetModel() *plugin.TValue[string] {
	return &c.Model
}

func (c *mqlJamfComputer) GetOperatingSystemName() *plugin.TValue[string] {
	return &c.OperatingSystemName
}

func (c *mqlJamfComputer) GetOperatingSystemVersion() *plugin.TValue[string] {
	return &c.OperatingSystemVersion
}

func (c *mqlJamfComputer) GetMacAddress() *plugin.TValue[string] {
	return &c.MacAddress
}

func (c *mqlJamfComputer) GetSerialNumber() *plugin.TValue[string] {
	return &c.SerialNumber
}

func (c *mqlJamfComputer) GetProcessorType() *plugin.TValue[string] {
	return &c.ProcessorType
}

func (c *mqlJamfComputer) GetProcessorCount() *plugin.TValue[int64] {
	return &c.ProcessorCount
}

func (c *mqlJamfComputer) GetCoreCount() *plugin.TValue[int64] {
	return &c.CoreCount
}

func (c *mqlJamfComputer) GetTotalRamMegabytes() *plugin.TValue[int64] {
	return &c.TotalRamMegabytes
}

func (c *mqlJamfComputer) GetLastIpAddress() *plugin.TValue[string] {
	return &c.LastIpAddress
}

func (c *mqlJamfComputer) GetLastReportedIp() *plugin.TValue[string] {
	return &c.LastReportedIp
}

func (c *mqlJamfComputer) GetJamfBinaryVersion() *plugin.TValue[string] {
	return &c.JamfBinaryVersion
}

func (c *mqlJamfComputer) GetPlatform() *plugin.TValue[string] {
	return &c.Platform
}

func (c *mqlJamfComputer) GetReportDate() *plugin.TValue[string] {
	return &c.ReportDate
}

func (c *mqlJamfComputer) GetLastContactTime() *plugin.TValue[string] {
	return &c.LastContactTime
}

func (c *mqlJamfComputer) GetLastEnrolledDate() *plugin.TValue[string] {
	return &c.LastEnrolledDate
}

func (c *mqlJamfComputer) GetInitialEntryDate() *plugin.TValue[string] {
	return &c.InitialEntryDate
}

func (c *mqlJamfComputer) GetItunesStoreAccountActive() *plugin.TValue[bool] {
	return &c.ItunesStoreAccountActive
}

func (c *mqlJamfComputer) GetEnrolledViaAutomatedDeviceEnrollment() *plugin.TValue[bool] {
	return &c.EnrolledViaAutomatedDeviceEnrollment
}

func (c *mqlJamfComputer) GetFileVault2Enabled() *plugin.TValue[string] {
	return &c.FileVault2Enabled
}

func (c *mqlJamfComputer) GetAutoLoginDisabled() *plugin.TValue[bool] {
	return &c.AutoLoginDisabled
}

func (c *mqlJamfComputer) GetActivationLockEnabled() *plugin.TValue[bool] {
	return &c.ActivationLockEnabled
}

func (c *mqlJamfComputer) GetFirewallEnabled() *plugin.TValue[bool] {
	return &c.FirewallEnabled
}

func (c *mqlJamfComputer) GetLocalUserAccounts() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.LocalUserAccounts, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("jamfComputer", c.__id, "localUserAccounts")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.localUserAccounts()
	})
}

// mqlJamfLocalUserAccount for the jamfLocalUserAccount resource
type mqlJamfLocalUserAccount struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJamfLocalUserAccountInternal it will be used here
	Uid                          plugin.TValue[string]
	Username                     plugin.TValue[string]
	FullName                     plugin.TValue[string]
	Admin                        plugin.TValue[bool]
	FileVault2Enabled            plugin.TValue[bool]
	UserAccountType              plugin.TValue[string]
	PasswordMaxAge               plugin.TValue[int64]
	HomeDirectory                plugin.TValue[string]
	PasswordMinLength            plugin.TValue[int64]
	PasswordMinComplexCharacters plugin.TValue[int64]
}

// createJamfLocalUserAccount creates a new instance of this resource
func createJamfLocalUserAccount(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJamfLocalUserAccount{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jamfLocalUserAccount", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJamfLocalUserAccount) MqlName() string {
	return "jamfLocalUserAccount"
}

func (c *mqlJamfLocalUserAccount) MqlID() string {
	return c.__id
}

func (c *mqlJamfLocalUserAccount) GetUid() *plugin.TValue[string] {
	return &c.Uid
}

func (c *mqlJamfLocalUserAccount) GetUsername() *plugin.TValue[string] {
	return &c.Username
}

func (c *mqlJamfLocalUserAccount) GetFullName() *plugin.TValue[string] {
	return &c.FullName
}

func (c *mqlJamfLocalUserAccount) GetAdmin() *plugin.TValue[bool] {
	return &c.Admin
}

func (c *mqlJamfLocalUserAccount) GetFileVault2Enabled() *plugin.TValue[bool] {
	return &c.FileVault2Enabled
}

func (c *mqlJamfLocalUserAccount) GetUserAccountType() *plugin.TValue[string] {
	return &c.UserAccountType
}

func (c *mqlJamfLocalUserAccount) GetPasswordMaxAge() *plugin.TValue[int64] {
	return &c.PasswordMaxAge
}

func (c *mqlJamfLocalUserAccount) GetHomeDirectory() *plugin.TValue[string] {
	return &c.HomeDirectory
}

func (c *mqlJamfLocalUserAccount) GetPasswordMinLength() *plugin.TValue[int64] {
	return &c.PasswordMinLength
}

func (c *mqlJamfLocalUserAccount) GetPasswordMinComplexCharacters() *plugin.TValue[int64] {
	return &c.PasswordMinComplexCharacters
}

// mqlSsoSettings for the ssoSettings resource
type mqlSsoSettings struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlSsoSettingsInternal it will be used here
	SsoEnabled                                     plugin.TValue[bool]
	SsoForEnrollmentEnabled                        plugin.TValue[bool]
	SsoBypassAllowed                               plugin.TValue[bool]
	SessionTimeout                                 plugin.TValue[int64]
	SsoForMacOsSelfServiceEnabled                  plugin.TValue[bool]
	TokenExpirationDisabled                        plugin.TValue[bool]
	UserAttributeEnabled                           plugin.TValue[bool]
	UserAttributeName                              plugin.TValue[string]
	UserMapping                                    plugin.TValue[string]
	EnrollmentSsoForAccountDrivenEnrollmentEnabled plugin.TValue[bool]
	IdpUrl                                         plugin.TValue[string]
	IdpProviderType                                plugin.TValue[string]
	GroupEnrollmentAccessEnabled                   plugin.TValue[bool]
	GroupAttributeName                             plugin.TValue[string]
	EntityId                                       plugin.TValue[string]
}

// createSsoSettings creates a new instance of this resource
func createSsoSettings(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlSsoSettings{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	// to override __id implement: id() (string, error)

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("ssoSettings", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlSsoSettings) MqlName() string {
	return "ssoSettings"
}

func (c *mqlSsoSettings) MqlID() string {
	return c.__id
}

func (c *mqlSsoSettings) GetSsoEnabled() *plugin.TValue[bool] {
	return &c.SsoEnabled
}

func (c *mqlSsoSettings) GetSsoForEnrollmentEnabled() *plugin.TValue[bool] {
	return &c.SsoForEnrollmentEnabled
}

func (c *mqlSsoSettings) GetSsoBypassAllowed() *plugin.TValue[bool] {
	return &c.SsoBypassAllowed
}

func (c *mqlSsoSettings) GetSessionTimeout() *plugin.TValue[int64] {
	return &c.SessionTimeout
}

func (c *mqlSsoSettings) GetSsoForMacOsSelfServiceEnabled() *plugin.TValue[bool] {
	return &c.SsoForMacOsSelfServiceEnabled
}

func (c *mqlSsoSettings) GetTokenExpirationDisabled() *plugin.TValue[bool] {
	return &c.TokenExpirationDisabled
}

func (c *mqlSsoSettings) GetUserAttributeEnabled() *plugin.TValue[bool] {
	return &c.UserAttributeEnabled
}

func (c *mqlSsoSettings) GetUserAttributeName() *plugin.TValue[string] {
	return &c.UserAttributeName
}

func (c *mqlSsoSettings) GetUserMapping() *plugin.TValue[string] {
	return &c.UserMapping
}

func (c *mqlSsoSettings) GetEnrollmentSsoForAccountDrivenEnrollmentEnabled() *plugin.TValue[bool] {
	return &c.EnrollmentSsoForAccountDrivenEnrollmentEnabled
}

func (c *mqlSsoSettings) GetIdpUrl() *plugin.TValue[string] {
	return &c.IdpUrl
}

func (c *mqlSsoSettings) GetIdpProviderType() *plugin.TValue[string] {
	return &c.IdpProviderType
}

func (c *mqlSsoSettings) GetGroupEnrollmentAccessEnabled() *plugin.TValue[bool] {
	return &c.GroupEnrollmentAccessEnabled
}

func (c *mqlSsoSettings) GetGroupAttributeName() *plugin.TValue[string] {
	return &c.GroupAttributeName
}

func (c *mqlSsoSettings) GetEntityId() *plugin.TValue[string] {
	return &c.EntityId
}

// mqlJamfUsers for the jamfUsers resource
type mqlJamfUsers struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJamfUsersInternal it will be used here
	Id   plugin.TValue[int64]
	Name plugin.TValue[string]
}

// createJamfUsers creates a new instance of this resource
func createJamfUsers(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJamfUsers{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jamfUsers", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJamfUsers) MqlName() string {
	return "jamfUsers"
}

func (c *mqlJamfUsers) MqlID() string {
	return c.__id
}

func (c *mqlJamfUsers) GetId() *plugin.TValue[int64] {
	return &c.Id
}

func (c *mqlJamfUsers) GetName() *plugin.TValue[string] {
	return &c.Name
}

// mqlJamfPackages for the jamfPackages resource
type mqlJamfPackages struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlJamfPackagesInternal it will be used here
	Name                 plugin.TValue[string]
	FileName             plugin.TValue[string]
	OSInstall            plugin.TValue[bool]
	CategoryId           plugin.TValue[string]
	Priority             plugin.TValue[int64]
	SuppressUpdates      plugin.TValue[bool]
	SuppressRegistration plugin.TValue[bool]
}

// createJamfPackages creates a new instance of this resource
func createJamfPackages(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlJamfPackages{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("jamfPackages", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlJamfPackages) MqlName() string {
	return "jamfPackages"
}

func (c *mqlJamfPackages) MqlID() string {
	return c.__id
}

func (c *mqlJamfPackages) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlJamfPackages) GetFileName() *plugin.TValue[string] {
	return &c.FileName
}

func (c *mqlJamfPackages) GetOSInstall() *plugin.TValue[bool] {
	return &c.OSInstall
}

func (c *mqlJamfPackages) GetCategoryId() *plugin.TValue[string] {
	return &c.CategoryId
}

func (c *mqlJamfPackages) GetPriority() *plugin.TValue[int64] {
	return &c.Priority
}

func (c *mqlJamfPackages) GetSuppressUpdates() *plugin.TValue[bool] {
	return &c.SuppressUpdates
}

func (c *mqlJamfPackages) GetSuppressRegistration() *plugin.TValue[bool] {
	return &c.SuppressRegistration
}
