// Copyright Mondoo, Inc. 2024, 2026
// SPDX-License-Identifier: BUSL-1.1

// Code generated by resources. DO NOT EDIT.

package resources

import (
	"errors"
	"time"

	"go.mondoo.com/mql/v13/llx"
	"go.mondoo.com/mql/v13/providers-sdk/v1/plugin"
	"go.mondoo.com/mql/v13/types"
)

// The MQL type names exposed as public consts for ease of reference.
const (
	ResourcePostgresql                   string = "postgresql"
	ResourcePostgresqlDatabase           string = "postgresql.database"
	ResourcePostgresqlRole               string = "postgresql.role"
	ResourcePostgresqlExtension          string = "postgresql.extension"
	ResourcePostgresqlAvailableExtension string = "postgresql.availableExtension"
	ResourcePostgresqlSetting            string = "postgresql.setting"
	ResourcePostgresqlHbaRule            string = "postgresql.hbaRule"
	ResourcePostgresqlIdentRule          string = "postgresql.identRule"
	ResourcePostgresqlReplicationSlot    string = "postgresql.replicationSlot"
	ResourcePostgresqlPublication        string = "postgresql.publication"
	ResourcePostgresqlSubscription       string = "postgresql.subscription"
	ResourcePostgresqlTablespace         string = "postgresql.tablespace"
	ResourcePostgresqlLanguage           string = "postgresql.language"
)

var resourceFactories map[string]plugin.ResourceFactory

func init() {
	resourceFactories = map[string]plugin.ResourceFactory{
		"postgresql": {
			// to override args, implement: initPostgresql(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresql,
		},
		"postgresql.database": {
			// to override args, implement: initPostgresqlDatabase(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlDatabase,
		},
		"postgresql.role": {
			// to override args, implement: initPostgresqlRole(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlRole,
		},
		"postgresql.extension": {
			// to override args, implement: initPostgresqlExtension(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlExtension,
		},
		"postgresql.availableExtension": {
			// to override args, implement: initPostgresqlAvailableExtension(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlAvailableExtension,
		},
		"postgresql.setting": {
			// to override args, implement: initPostgresqlSetting(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlSetting,
		},
		"postgresql.hbaRule": {
			// to override args, implement: initPostgresqlHbaRule(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlHbaRule,
		},
		"postgresql.identRule": {
			// to override args, implement: initPostgresqlIdentRule(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlIdentRule,
		},
		"postgresql.replicationSlot": {
			// to override args, implement: initPostgresqlReplicationSlot(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlReplicationSlot,
		},
		"postgresql.publication": {
			// to override args, implement: initPostgresqlPublication(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlPublication,
		},
		"postgresql.subscription": {
			// to override args, implement: initPostgresqlSubscription(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlSubscription,
		},
		"postgresql.tablespace": {
			// to override args, implement: initPostgresqlTablespace(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlTablespace,
		},
		"postgresql.language": {
			// to override args, implement: initPostgresqlLanguage(runtime *plugin.Runtime, args map[string]*llx.RawData) (map[string]*llx.RawData, plugin.Resource, error)
			Create: createPostgresqlLanguage,
		},
	}
}

// NewResource is used by the runtime of this plugin to create new resources.
// Its arguments may be provided by users. This function is generally not
// used by initializing resources from recordings or from lists.
func NewResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	if f.Init != nil {
		cargs, res, err := f.Init(runtime, args)
		if err != nil {
			return res, err
		}

		if res != nil {
			mqlId := res.MqlID()
			id := name + "\x00" + mqlId
			if x, ok := runtime.Resources.Get(id); ok {
				return x, nil
			}
			runtime.Resources.Set(id, res)
			return res, nil
		}

		args = cargs
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

// CreateResource is used by the runtime of this plugin to create resources.
// Its arguments must be complete and pre-processed. This method is used
// for initializing resources from recordings or from lists.
func CreateResource(runtime *plugin.Runtime, name string, args map[string]*llx.RawData) (plugin.Resource, error) {
	f, ok := resourceFactories[name]
	if !ok {
		return nil, errors.New("cannot find resource " + name + " in this provider")
	}

	res, err := f.Create(runtime, args)
	if err != nil {
		return nil, err
	}

	mqlId := res.MqlID()
	id := name + "\x00" + mqlId
	if x, ok := runtime.Resources.Get(id); ok {
		return x, nil
	}

	runtime.Resources.Set(id, res)
	return res, nil
}

var getDataFields = map[string]func(r plugin.Resource) *plugin.DataRes{
	"postgresql.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetVersion()).ToDataRes(types.String)
	},
	"postgresql.versionNum": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetVersionNum()).ToDataRes(types.Int)
	},
	"postgresql.currentDatabase": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetCurrentDatabase()).ToDataRes(types.String)
	},
	"postgresql.currentUser": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetCurrentUser()).ToDataRes(types.String)
	},
	"postgresql.startedAt": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetStartedAt()).ToDataRes(types.Time)
	},
	"postgresql.inRecovery": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetInRecovery()).ToDataRes(types.Bool)
	},
	"postgresql.databases": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetDatabases()).ToDataRes(types.Array(types.Resource("postgresql.database")))
	},
	"postgresql.roles": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetRoles()).ToDataRes(types.Array(types.Resource("postgresql.role")))
	},
	"postgresql.extensions": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetExtensions()).ToDataRes(types.Array(types.Resource("postgresql.extension")))
	},
	"postgresql.availableExtensions": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetAvailableExtensions()).ToDataRes(types.Array(types.Resource("postgresql.availableExtension")))
	},
	"postgresql.settings": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetSettings()).ToDataRes(types.Array(types.Resource("postgresql.setting")))
	},
	"postgresql.hbaRules": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetHbaRules()).ToDataRes(types.Array(types.Resource("postgresql.hbaRule")))
	},
	"postgresql.identRules": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetIdentRules()).ToDataRes(types.Array(types.Resource("postgresql.identRule")))
	},
	"postgresql.replicationSlots": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetReplicationSlots()).ToDataRes(types.Array(types.Resource("postgresql.replicationSlot")))
	},
	"postgresql.publications": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetPublications()).ToDataRes(types.Array(types.Resource("postgresql.publication")))
	},
	"postgresql.subscriptions": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetSubscriptions()).ToDataRes(types.Array(types.Resource("postgresql.subscription")))
	},
	"postgresql.tablespaces": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetTablespaces()).ToDataRes(types.Array(types.Resource("postgresql.tablespace")))
	},
	"postgresql.languages": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresql).GetLanguages()).ToDataRes(types.Array(types.Resource("postgresql.language")))
	},
	"postgresql.database.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetOid()).ToDataRes(types.Int)
	},
	"postgresql.database.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetName()).ToDataRes(types.String)
	},
	"postgresql.database.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetOwner()).ToDataRes(types.String)
	},
	"postgresql.database.encoding": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetEncoding()).ToDataRes(types.String)
	},
	"postgresql.database.collation": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetCollation()).ToDataRes(types.String)
	},
	"postgresql.database.ctype": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetCtype()).ToDataRes(types.String)
	},
	"postgresql.database.tablespace": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetTablespace()).ToDataRes(types.String)
	},
	"postgresql.database.allowConnections": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetAllowConnections()).ToDataRes(types.Bool)
	},
	"postgresql.database.isTemplate": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetIsTemplate()).ToDataRes(types.Bool)
	},
	"postgresql.database.connectionLimit": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetConnectionLimit()).ToDataRes(types.Int)
	},
	"postgresql.database.sizeBytes": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlDatabase).GetSizeBytes()).ToDataRes(types.Int)
	},
	"postgresql.role.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetOid()).ToDataRes(types.Int)
	},
	"postgresql.role.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetName()).ToDataRes(types.String)
	},
	"postgresql.role.superuser": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetSuperuser()).ToDataRes(types.Bool)
	},
	"postgresql.role.canBeInherited": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetCanBeInherited()).ToDataRes(types.Bool)
	},
	"postgresql.role.createDb": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetCreateDb()).ToDataRes(types.Bool)
	},
	"postgresql.role.createRole": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetCreateRole()).ToDataRes(types.Bool)
	},
	"postgresql.role.login": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetLogin()).ToDataRes(types.Bool)
	},
	"postgresql.role.replication": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetReplication()).ToDataRes(types.Bool)
	},
	"postgresql.role.bypassRls": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetBypassRls()).ToDataRes(types.Bool)
	},
	"postgresql.role.connectionLimit": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetConnectionLimit()).ToDataRes(types.Int)
	},
	"postgresql.role.validUntil": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetValidUntil()).ToDataRes(types.Time)
	},
	"postgresql.role.memberOf": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlRole).GetMemberOf()).ToDataRes(types.Array(types.String))
	},
	"postgresql.extension.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlExtension).GetOid()).ToDataRes(types.Int)
	},
	"postgresql.extension.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlExtension).GetName()).ToDataRes(types.String)
	},
	"postgresql.extension.version": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlExtension).GetVersion()).ToDataRes(types.String)
	},
	"postgresql.extension.schema": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlExtension).GetSchema()).ToDataRes(types.String)
	},
	"postgresql.extension.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlExtension).GetOwner()).ToDataRes(types.String)
	},
	"postgresql.extension.relocatable": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlExtension).GetRelocatable()).ToDataRes(types.Bool)
	},
	"postgresql.availableExtension.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlAvailableExtension).GetName()).ToDataRes(types.String)
	},
	"postgresql.availableExtension.defaultVersion": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlAvailableExtension).GetDefaultVersion()).ToDataRes(types.String)
	},
	"postgresql.availableExtension.installedVersion": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlAvailableExtension).GetInstalledVersion()).ToDataRes(types.String)
	},
	"postgresql.availableExtension.comment": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlAvailableExtension).GetComment()).ToDataRes(types.String)
	},
	"postgresql.setting.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetName()).ToDataRes(types.String)
	},
	"postgresql.setting.value": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetValue()).ToDataRes(types.String)
	},
	"postgresql.setting.unit": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetUnit()).ToDataRes(types.String)
	},
	"postgresql.setting.category": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetCategory()).ToDataRes(types.String)
	},
	"postgresql.setting.shortDesc": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetShortDesc()).ToDataRes(types.String)
	},
	"postgresql.setting.extraDesc": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetExtraDesc()).ToDataRes(types.String)
	},
	"postgresql.setting.source": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetSource()).ToDataRes(types.String)
	},
	"postgresql.setting.sourceFile": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetSourceFile()).ToDataRes(types.String)
	},
	"postgresql.setting.sourceLine": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetSourceLine()).ToDataRes(types.Int)
	},
	"postgresql.setting.context": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetContext()).ToDataRes(types.String)
	},
	"postgresql.setting.vartype": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetVartype()).ToDataRes(types.String)
	},
	"postgresql.setting.enumValues": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetEnumValues()).ToDataRes(types.Array(types.String))
	},
	"postgresql.setting.minVal": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetMinVal()).ToDataRes(types.String)
	},
	"postgresql.setting.maxVal": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetMaxVal()).ToDataRes(types.String)
	},
	"postgresql.setting.bootVal": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetBootVal()).ToDataRes(types.String)
	},
	"postgresql.setting.resetVal": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetResetVal()).ToDataRes(types.String)
	},
	"postgresql.setting.pendingRestart": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSetting).GetPendingRestart()).ToDataRes(types.Bool)
	},
	"postgresql.hbaRule.lineNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetLineNumber()).ToDataRes(types.Int)
	},
	"postgresql.hbaRule.fileName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetFileName()).ToDataRes(types.String)
	},
	"postgresql.hbaRule.type": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetType()).ToDataRes(types.String)
	},
	"postgresql.hbaRule.databases": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetDatabases()).ToDataRes(types.Array(types.String))
	},
	"postgresql.hbaRule.userNames": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetUserNames()).ToDataRes(types.Array(types.String))
	},
	"postgresql.hbaRule.address": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetAddress()).ToDataRes(types.String)
	},
	"postgresql.hbaRule.netmask": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetNetmask()).ToDataRes(types.String)
	},
	"postgresql.hbaRule.authMethod": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetAuthMethod()).ToDataRes(types.String)
	},
	"postgresql.hbaRule.options": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetOptions()).ToDataRes(types.Map(types.String, types.String))
	},
	"postgresql.hbaRule.error": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlHbaRule).GetError()).ToDataRes(types.String)
	},
	"postgresql.identRule.lineNumber": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlIdentRule).GetLineNumber()).ToDataRes(types.Int)
	},
	"postgresql.identRule.fileName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlIdentRule).GetFileName()).ToDataRes(types.String)
	},
	"postgresql.identRule.mapName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlIdentRule).GetMapName()).ToDataRes(types.String)
	},
	"postgresql.identRule.systemUsername": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlIdentRule).GetSystemUsername()).ToDataRes(types.String)
	},
	"postgresql.identRule.pgUsername": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlIdentRule).GetPgUsername()).ToDataRes(types.String)
	},
	"postgresql.identRule.error": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlIdentRule).GetError()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.slotName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetSlotName()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.plugin": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetPlugin()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.slotType": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetSlotType()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.database": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetDatabase()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.active": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetActive()).ToDataRes(types.Bool)
	},
	"postgresql.replicationSlot.activePid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetActivePid()).ToDataRes(types.Int)
	},
	"postgresql.replicationSlot.temporary": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetTemporary()).ToDataRes(types.Bool)
	},
	"postgresql.replicationSlot.restartLsn": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetRestartLsn()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.confirmedFlushLsn": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetConfirmedFlushLsn()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.walStatus": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetWalStatus()).ToDataRes(types.String)
	},
	"postgresql.replicationSlot.twoPhase": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlReplicationSlot).GetTwoPhase()).ToDataRes(types.Bool)
	},
	"postgresql.publication.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetOid()).ToDataRes(types.Int)
	},
	"postgresql.publication.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetName()).ToDataRes(types.String)
	},
	"postgresql.publication.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetOwner()).ToDataRes(types.String)
	},
	"postgresql.publication.allTables": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetAllTables()).ToDataRes(types.Bool)
	},
	"postgresql.publication.insertEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetInsertEnabled()).ToDataRes(types.Bool)
	},
	"postgresql.publication.updateEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetUpdateEnabled()).ToDataRes(types.Bool)
	},
	"postgresql.publication.deleteEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetDeleteEnabled()).ToDataRes(types.Bool)
	},
	"postgresql.publication.truncateEnabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlPublication).GetTruncateEnabled()).ToDataRes(types.Bool)
	},
	"postgresql.subscription.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetOid()).ToDataRes(types.Int)
	},
	"postgresql.subscription.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetName()).ToDataRes(types.String)
	},
	"postgresql.subscription.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetOwner()).ToDataRes(types.String)
	},
	"postgresql.subscription.enabled": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetEnabled()).ToDataRes(types.Bool)
	},
	"postgresql.subscription.connInfo": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetConnInfo()).ToDataRes(types.String)
	},
	"postgresql.subscription.slotName": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetSlotName()).ToDataRes(types.String)
	},
	"postgresql.subscription.synchronousCommit": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetSynchronousCommit()).ToDataRes(types.String)
	},
	"postgresql.subscription.publicationNames": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlSubscription).GetPublicationNames()).ToDataRes(types.Array(types.String))
	},
	"postgresql.tablespace.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlTablespace).GetOid()).ToDataRes(types.Int)
	},
	"postgresql.tablespace.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlTablespace).GetName()).ToDataRes(types.String)
	},
	"postgresql.tablespace.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlTablespace).GetOwner()).ToDataRes(types.String)
	},
	"postgresql.tablespace.location": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlTablespace).GetLocation()).ToDataRes(types.String)
	},
	"postgresql.language.oid": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlLanguage).GetOid()).ToDataRes(types.Int)
	},
	"postgresql.language.name": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlLanguage).GetName()).ToDataRes(types.String)
	},
	"postgresql.language.owner": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlLanguage).GetOwner()).ToDataRes(types.String)
	},
	"postgresql.language.trusted": func(r plugin.Resource) *plugin.DataRes {
		return (r.(*mqlPostgresqlLanguage).GetTrusted()).ToDataRes(types.Bool)
	},
}

func GetData(resource plugin.Resource, field string, args map[string]*llx.RawData) *plugin.DataRes {
	f, ok := getDataFields[resource.MqlName()+"."+field]
	if !ok {
		return &plugin.DataRes{Error: "cannot find '" + field + "' in resource '" + resource.MqlName() + "'"}
	}

	return f(resource)
}

var setDataFields = map[string]func(r plugin.Resource, v *llx.RawData) bool{
	"postgresql.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).__id, ok = v.Value.(string)
		return
	},
	"postgresql.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.versionNum": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).VersionNum, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.currentDatabase": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).CurrentDatabase, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.currentUser": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).CurrentUser, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.startedAt": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).StartedAt, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"postgresql.inRecovery": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).InRecovery, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.databases": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Databases, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.roles": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Roles, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.extensions": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Extensions, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.availableExtensions": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).AvailableExtensions, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.settings": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Settings, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.hbaRules": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).HbaRules, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.identRules": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).IdentRules, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlots": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).ReplicationSlots, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.publications": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Publications, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.subscriptions": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Subscriptions, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.tablespaces": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Tablespaces, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.languages": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresql).Languages, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.database.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).__id, ok = v.Value.(string)
		return
	},
	"postgresql.database.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.database.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.database.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).Owner, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.database.encoding": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).Encoding, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.database.collation": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).Collation, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.database.ctype": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).Ctype, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.database.tablespace": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).Tablespace, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.database.allowConnections": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).AllowConnections, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.database.isTemplate": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).IsTemplate, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.database.connectionLimit": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).ConnectionLimit, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.database.sizeBytes": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlDatabase).SizeBytes, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.role.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).__id, ok = v.Value.(string)
		return
	},
	"postgresql.role.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.role.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.role.superuser": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).Superuser, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.role.canBeInherited": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).CanBeInherited, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.role.createDb": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).CreateDb, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.role.createRole": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).CreateRole, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.role.login": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).Login, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.role.replication": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).Replication, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.role.bypassRls": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).BypassRls, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.role.connectionLimit": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).ConnectionLimit, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.role.validUntil": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).ValidUntil, ok = plugin.RawToTValue[*time.Time](v.Value, v.Error)
		return
	},
	"postgresql.role.memberOf": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlRole).MemberOf, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.extension.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlExtension).__id, ok = v.Value.(string)
		return
	},
	"postgresql.extension.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlExtension).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.extension.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlExtension).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.extension.version": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlExtension).Version, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.extension.schema": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlExtension).Schema, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.extension.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlExtension).Owner, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.extension.relocatable": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlExtension).Relocatable, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.availableExtension.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlAvailableExtension).__id, ok = v.Value.(string)
		return
	},
	"postgresql.availableExtension.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlAvailableExtension).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.availableExtension.defaultVersion": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlAvailableExtension).DefaultVersion, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.availableExtension.installedVersion": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlAvailableExtension).InstalledVersion, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.availableExtension.comment": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlAvailableExtension).Comment, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).__id, ok = v.Value.(string)
		return
	},
	"postgresql.setting.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.value": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).Value, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.unit": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).Unit, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.category": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).Category, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.shortDesc": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).ShortDesc, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.extraDesc": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).ExtraDesc, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.source": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).Source, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.sourceFile": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).SourceFile, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.sourceLine": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).SourceLine, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.setting.context": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).Context, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.vartype": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).Vartype, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.enumValues": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).EnumValues, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.setting.minVal": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).MinVal, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.maxVal": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).MaxVal, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.bootVal": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).BootVal, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.resetVal": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).ResetVal, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.setting.pendingRestart": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSetting).PendingRestart, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).__id, ok = v.Value.(string)
		return
	},
	"postgresql.hbaRule.lineNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).LineNumber, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.fileName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).FileName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.type": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).Type, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.databases": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).Databases, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.userNames": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).UserNames, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.address": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).Address, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.netmask": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).Netmask, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.authMethod": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).AuthMethod, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.options": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).Options, ok = plugin.RawToTValue[map[string]any](v.Value, v.Error)
		return
	},
	"postgresql.hbaRule.error": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlHbaRule).Error, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.identRule.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlIdentRule).__id, ok = v.Value.(string)
		return
	},
	"postgresql.identRule.lineNumber": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlIdentRule).LineNumber, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.identRule.fileName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlIdentRule).FileName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.identRule.mapName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlIdentRule).MapName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.identRule.systemUsername": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlIdentRule).SystemUsername, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.identRule.pgUsername": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlIdentRule).PgUsername, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.identRule.error": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlIdentRule).Error, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).__id, ok = v.Value.(string)
		return
	},
	"postgresql.replicationSlot.slotName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).SlotName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.plugin": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).Plugin, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.slotType": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).SlotType, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.database": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).Database, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.active": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).Active, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.activePid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).ActivePid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.temporary": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).Temporary, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.restartLsn": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).RestartLsn, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.confirmedFlushLsn": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).ConfirmedFlushLsn, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.walStatus": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).WalStatus, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.replicationSlot.twoPhase": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlReplicationSlot).TwoPhase, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.publication.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).__id, ok = v.Value.(string)
		return
	},
	"postgresql.publication.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.publication.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.publication.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).Owner, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.publication.allTables": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).AllTables, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.publication.insertEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).InsertEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.publication.updateEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).UpdateEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.publication.deleteEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).DeleteEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.publication.truncateEnabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlPublication).TruncateEnabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.subscription.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).__id, ok = v.Value.(string)
		return
	},
	"postgresql.subscription.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.subscription.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.subscription.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).Owner, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.subscription.enabled": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).Enabled, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
	"postgresql.subscription.connInfo": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).ConnInfo, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.subscription.slotName": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).SlotName, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.subscription.synchronousCommit": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).SynchronousCommit, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.subscription.publicationNames": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlSubscription).PublicationNames, ok = plugin.RawToTValue[[]any](v.Value, v.Error)
		return
	},
	"postgresql.tablespace.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlTablespace).__id, ok = v.Value.(string)
		return
	},
	"postgresql.tablespace.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlTablespace).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.tablespace.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlTablespace).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.tablespace.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlTablespace).Owner, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.tablespace.location": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlTablespace).Location, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.language.__id": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlLanguage).__id, ok = v.Value.(string)
		return
	},
	"postgresql.language.oid": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlLanguage).Oid, ok = plugin.RawToTValue[int64](v.Value, v.Error)
		return
	},
	"postgresql.language.name": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlLanguage).Name, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.language.owner": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlLanguage).Owner, ok = plugin.RawToTValue[string](v.Value, v.Error)
		return
	},
	"postgresql.language.trusted": func(r plugin.Resource, v *llx.RawData) (ok bool) {
		r.(*mqlPostgresqlLanguage).Trusted, ok = plugin.RawToTValue[bool](v.Value, v.Error)
		return
	},
}

func SetData(resource plugin.Resource, field string, val *llx.RawData) error {
	f, ok := setDataFields[resource.MqlName()+"."+field]
	if !ok {
		return errors.New("[postgres] cannot set '" + field + "' in resource '" + resource.MqlName() + "', field not found")
	}

	if ok := f(resource, val); !ok {
		return errors.New("[postgres] cannot set '" + field + "' in resource '" + resource.MqlName() + "', type does not match")
	}
	return nil
}

func SetAllData(resource plugin.Resource, args map[string]*llx.RawData) error {
	var err error
	for k, v := range args {
		if err = SetData(resource, k, v); err != nil {
			return err
		}
	}
	return nil
}

// mqlPostgresql for the postgresql resource
type mqlPostgresql struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlInternal it will be used here
	Version             plugin.TValue[string]
	VersionNum          plugin.TValue[int64]
	CurrentDatabase     plugin.TValue[string]
	CurrentUser         plugin.TValue[string]
	StartedAt           plugin.TValue[*time.Time]
	InRecovery          plugin.TValue[bool]
	Databases           plugin.TValue[[]any]
	Roles               plugin.TValue[[]any]
	Extensions          plugin.TValue[[]any]
	AvailableExtensions plugin.TValue[[]any]
	Settings            plugin.TValue[[]any]
	HbaRules            plugin.TValue[[]any]
	IdentRules          plugin.TValue[[]any]
	ReplicationSlots    plugin.TValue[[]any]
	Publications        plugin.TValue[[]any]
	Subscriptions       plugin.TValue[[]any]
	Tablespaces         plugin.TValue[[]any]
	Languages           plugin.TValue[[]any]
}

// createPostgresql creates a new instance of this resource
func createPostgresql(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresql{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresql) MqlName() string {
	return "postgresql"
}

func (c *mqlPostgresql) MqlID() string {
	return c.__id
}

func (c *mqlPostgresql) GetVersion() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.Version, func() (string, error) {
		return c.version()
	})
}

func (c *mqlPostgresql) GetVersionNum() *plugin.TValue[int64] {
	return plugin.GetOrCompute[int64](&c.VersionNum, func() (int64, error) {
		return c.versionNum()
	})
}

func (c *mqlPostgresql) GetCurrentDatabase() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.CurrentDatabase, func() (string, error) {
		return c.currentDatabase()
	})
}

func (c *mqlPostgresql) GetCurrentUser() *plugin.TValue[string] {
	return plugin.GetOrCompute[string](&c.CurrentUser, func() (string, error) {
		return c.currentUser()
	})
}

func (c *mqlPostgresql) GetStartedAt() *plugin.TValue[*time.Time] {
	return plugin.GetOrCompute[*time.Time](&c.StartedAt, func() (*time.Time, error) {
		return c.startedAt()
	})
}

func (c *mqlPostgresql) GetInRecovery() *plugin.TValue[bool] {
	return plugin.GetOrCompute[bool](&c.InRecovery, func() (bool, error) {
		return c.inRecovery()
	})
}

func (c *mqlPostgresql) GetDatabases() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Databases, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "databases")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.databases()
	})
}

func (c *mqlPostgresql) GetRoles() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Roles, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "roles")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.roles()
	})
}

func (c *mqlPostgresql) GetExtensions() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Extensions, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "extensions")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.extensions()
	})
}

func (c *mqlPostgresql) GetAvailableExtensions() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.AvailableExtensions, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "availableExtensions")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.availableExtensions()
	})
}

func (c *mqlPostgresql) GetSettings() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Settings, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "settings")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.settings()
	})
}

func (c *mqlPostgresql) GetHbaRules() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.HbaRules, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "hbaRules")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.hbaRules()
	})
}

func (c *mqlPostgresql) GetIdentRules() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.IdentRules, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "identRules")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.identRules()
	})
}

func (c *mqlPostgresql) GetReplicationSlots() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.ReplicationSlots, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "replicationSlots")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.replicationSlots()
	})
}

func (c *mqlPostgresql) GetPublications() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Publications, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "publications")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.publications()
	})
}

func (c *mqlPostgresql) GetSubscriptions() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Subscriptions, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "subscriptions")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.subscriptions()
	})
}

func (c *mqlPostgresql) GetTablespaces() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Tablespaces, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "tablespaces")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.tablespaces()
	})
}

func (c *mqlPostgresql) GetLanguages() *plugin.TValue[[]any] {
	return plugin.GetOrCompute[[]any](&c.Languages, func() ([]any, error) {
		if c.MqlRuntime.HasRecording {
			d, err := c.MqlRuntime.FieldResourceFromRecording("postgresql", c.__id, "languages")
			if err != nil {
				return nil, err
			}
			if d != nil {
				return d.Value.([]any), nil
			}
		}

		return c.languages()
	})
}

// mqlPostgresqlDatabase for the postgresql.database resource
type mqlPostgresqlDatabase struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlDatabaseInternal it will be used here
	Oid              plugin.TValue[int64]
	Name             plugin.TValue[string]
	Owner            plugin.TValue[string]
	Encoding         plugin.TValue[string]
	Collation        plugin.TValue[string]
	Ctype            plugin.TValue[string]
	Tablespace       plugin.TValue[string]
	AllowConnections plugin.TValue[bool]
	IsTemplate       plugin.TValue[bool]
	ConnectionLimit  plugin.TValue[int64]
	SizeBytes        plugin.TValue[int64]
}

// createPostgresqlDatabase creates a new instance of this resource
func createPostgresqlDatabase(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlDatabase{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.database", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlDatabase) MqlName() string {
	return "postgresql.database"
}

func (c *mqlPostgresqlDatabase) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlDatabase) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresqlDatabase) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlDatabase) GetOwner() *plugin.TValue[string] {
	return &c.Owner
}

func (c *mqlPostgresqlDatabase) GetEncoding() *plugin.TValue[string] {
	return &c.Encoding
}

func (c *mqlPostgresqlDatabase) GetCollation() *plugin.TValue[string] {
	return &c.Collation
}

func (c *mqlPostgresqlDatabase) GetCtype() *plugin.TValue[string] {
	return &c.Ctype
}

func (c *mqlPostgresqlDatabase) GetTablespace() *plugin.TValue[string] {
	return &c.Tablespace
}

func (c *mqlPostgresqlDatabase) GetAllowConnections() *plugin.TValue[bool] {
	return &c.AllowConnections
}

func (c *mqlPostgresqlDatabase) GetIsTemplate() *plugin.TValue[bool] {
	return &c.IsTemplate
}

func (c *mqlPostgresqlDatabase) GetConnectionLimit() *plugin.TValue[int64] {
	return &c.ConnectionLimit
}

func (c *mqlPostgresqlDatabase) GetSizeBytes() *plugin.TValue[int64] {
	return &c.SizeBytes
}

// mqlPostgresqlRole for the postgresql.role resource
type mqlPostgresqlRole struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlRoleInternal it will be used here
	Oid             plugin.TValue[int64]
	Name            plugin.TValue[string]
	Superuser       plugin.TValue[bool]
	CanBeInherited  plugin.TValue[bool]
	CreateDb        plugin.TValue[bool]
	CreateRole      plugin.TValue[bool]
	Login           plugin.TValue[bool]
	Replication     plugin.TValue[bool]
	BypassRls       plugin.TValue[bool]
	ConnectionLimit plugin.TValue[int64]
	ValidUntil      plugin.TValue[*time.Time]
	MemberOf        plugin.TValue[[]any]
}

// createPostgresqlRole creates a new instance of this resource
func createPostgresqlRole(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlRole{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.role", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlRole) MqlName() string {
	return "postgresql.role"
}

func (c *mqlPostgresqlRole) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlRole) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresqlRole) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlRole) GetSuperuser() *plugin.TValue[bool] {
	return &c.Superuser
}

func (c *mqlPostgresqlRole) GetCanBeInherited() *plugin.TValue[bool] {
	return &c.CanBeInherited
}

func (c *mqlPostgresqlRole) GetCreateDb() *plugin.TValue[bool] {
	return &c.CreateDb
}

func (c *mqlPostgresqlRole) GetCreateRole() *plugin.TValue[bool] {
	return &c.CreateRole
}

func (c *mqlPostgresqlRole) GetLogin() *plugin.TValue[bool] {
	return &c.Login
}

func (c *mqlPostgresqlRole) GetReplication() *plugin.TValue[bool] {
	return &c.Replication
}

func (c *mqlPostgresqlRole) GetBypassRls() *plugin.TValue[bool] {
	return &c.BypassRls
}

func (c *mqlPostgresqlRole) GetConnectionLimit() *plugin.TValue[int64] {
	return &c.ConnectionLimit
}

func (c *mqlPostgresqlRole) GetValidUntil() *plugin.TValue[*time.Time] {
	return &c.ValidUntil
}

func (c *mqlPostgresqlRole) GetMemberOf() *plugin.TValue[[]any] {
	return &c.MemberOf
}

// mqlPostgresqlExtension for the postgresql.extension resource
type mqlPostgresqlExtension struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlExtensionInternal it will be used here
	Oid         plugin.TValue[int64]
	Name        plugin.TValue[string]
	Version     plugin.TValue[string]
	Schema      plugin.TValue[string]
	Owner       plugin.TValue[string]
	Relocatable plugin.TValue[bool]
}

// createPostgresqlExtension creates a new instance of this resource
func createPostgresqlExtension(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlExtension{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.extension", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlExtension) MqlName() string {
	return "postgresql.extension"
}

func (c *mqlPostgresqlExtension) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlExtension) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresqlExtension) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlExtension) GetVersion() *plugin.TValue[string] {
	return &c.Version
}

func (c *mqlPostgresqlExtension) GetSchema() *plugin.TValue[string] {
	return &c.Schema
}

func (c *mqlPostgresqlExtension) GetOwner() *plugin.TValue[string] {
	return &c.Owner
}

func (c *mqlPostgresqlExtension) GetRelocatable() *plugin.TValue[bool] {
	return &c.Relocatable
}

// mqlPostgresqlAvailableExtension for the postgresql.availableExtension resource
type mqlPostgresqlAvailableExtension struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlAvailableExtensionInternal it will be used here
	Name             plugin.TValue[string]
	DefaultVersion   plugin.TValue[string]
	InstalledVersion plugin.TValue[string]
	Comment          plugin.TValue[string]
}

// createPostgresqlAvailableExtension creates a new instance of this resource
func createPostgresqlAvailableExtension(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlAvailableExtension{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.availableExtension", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlAvailableExtension) MqlName() string {
	return "postgresql.availableExtension"
}

func (c *mqlPostgresqlAvailableExtension) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlAvailableExtension) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlAvailableExtension) GetDefaultVersion() *plugin.TValue[string] {
	return &c.DefaultVersion
}

func (c *mqlPostgresqlAvailableExtension) GetInstalledVersion() *plugin.TValue[string] {
	return &c.InstalledVersion
}

func (c *mqlPostgresqlAvailableExtension) GetComment() *plugin.TValue[string] {
	return &c.Comment
}

// mqlPostgresqlSetting for the postgresql.setting resource
type mqlPostgresqlSetting struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlSettingInternal it will be used here
	Name           plugin.TValue[string]
	Value          plugin.TValue[string]
	Unit           plugin.TValue[string]
	Category       plugin.TValue[string]
	ShortDesc      plugin.TValue[string]
	ExtraDesc      plugin.TValue[string]
	Source         plugin.TValue[string]
	SourceFile     plugin.TValue[string]
	SourceLine     plugin.TValue[int64]
	Context        plugin.TValue[string]
	Vartype        plugin.TValue[string]
	EnumValues     plugin.TValue[[]any]
	MinVal         plugin.TValue[string]
	MaxVal         plugin.TValue[string]
	BootVal        plugin.TValue[string]
	ResetVal       plugin.TValue[string]
	PendingRestart plugin.TValue[bool]
}

// createPostgresqlSetting creates a new instance of this resource
func createPostgresqlSetting(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlSetting{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.setting", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlSetting) MqlName() string {
	return "postgresql.setting"
}

func (c *mqlPostgresqlSetting) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlSetting) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlSetting) GetValue() *plugin.TValue[string] {
	return &c.Value
}

func (c *mqlPostgresqlSetting) GetUnit() *plugin.TValue[string] {
	return &c.Unit
}

func (c *mqlPostgresqlSetting) GetCategory() *plugin.TValue[string] {
	return &c.Category
}

func (c *mqlPostgresqlSetting) GetShortDesc() *plugin.TValue[string] {
	return &c.ShortDesc
}

func (c *mqlPostgresqlSetting) GetExtraDesc() *plugin.TValue[string] {
	return &c.ExtraDesc
}

func (c *mqlPostgresqlSetting) GetSource() *plugin.TValue[string] {
	return &c.Source
}

func (c *mqlPostgresqlSetting) GetSourceFile() *plugin.TValue[string] {
	return &c.SourceFile
}

func (c *mqlPostgresqlSetting) GetSourceLine() *plugin.TValue[int64] {
	return &c.SourceLine
}

func (c *mqlPostgresqlSetting) GetContext() *plugin.TValue[string] {
	return &c.Context
}

func (c *mqlPostgresqlSetting) GetVartype() *plugin.TValue[string] {
	return &c.Vartype
}

func (c *mqlPostgresqlSetting) GetEnumValues() *plugin.TValue[[]any] {
	return &c.EnumValues
}

func (c *mqlPostgresqlSetting) GetMinVal() *plugin.TValue[string] {
	return &c.MinVal
}

func (c *mqlPostgresqlSetting) GetMaxVal() *plugin.TValue[string] {
	return &c.MaxVal
}

func (c *mqlPostgresqlSetting) GetBootVal() *plugin.TValue[string] {
	return &c.BootVal
}

func (c *mqlPostgresqlSetting) GetResetVal() *plugin.TValue[string] {
	return &c.ResetVal
}

func (c *mqlPostgresqlSetting) GetPendingRestart() *plugin.TValue[bool] {
	return &c.PendingRestart
}

// mqlPostgresqlHbaRule for the postgresql.hbaRule resource
type mqlPostgresqlHbaRule struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlHbaRuleInternal it will be used here
	LineNumber plugin.TValue[int64]
	FileName   plugin.TValue[string]
	Type       plugin.TValue[string]
	Databases  plugin.TValue[[]any]
	UserNames  plugin.TValue[[]any]
	Address    plugin.TValue[string]
	Netmask    plugin.TValue[string]
	AuthMethod plugin.TValue[string]
	Options    plugin.TValue[map[string]any]
	Error      plugin.TValue[string]
}

// createPostgresqlHbaRule creates a new instance of this resource
func createPostgresqlHbaRule(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlHbaRule{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.hbaRule", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlHbaRule) MqlName() string {
	return "postgresql.hbaRule"
}

func (c *mqlPostgresqlHbaRule) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlHbaRule) GetLineNumber() *plugin.TValue[int64] {
	return &c.LineNumber
}

func (c *mqlPostgresqlHbaRule) GetFileName() *plugin.TValue[string] {
	return &c.FileName
}

func (c *mqlPostgresqlHbaRule) GetType() *plugin.TValue[string] {
	return &c.Type
}

func (c *mqlPostgresqlHbaRule) GetDatabases() *plugin.TValue[[]any] {
	return &c.Databases
}

func (c *mqlPostgresqlHbaRule) GetUserNames() *plugin.TValue[[]any] {
	return &c.UserNames
}

func (c *mqlPostgresqlHbaRule) GetAddress() *plugin.TValue[string] {
	return &c.Address
}

func (c *mqlPostgresqlHbaRule) GetNetmask() *plugin.TValue[string] {
	return &c.Netmask
}

func (c *mqlPostgresqlHbaRule) GetAuthMethod() *plugin.TValue[string] {
	return &c.AuthMethod
}

func (c *mqlPostgresqlHbaRule) GetOptions() *plugin.TValue[map[string]any] {
	return &c.Options
}

func (c *mqlPostgresqlHbaRule) GetError() *plugin.TValue[string] {
	return &c.Error
}

// mqlPostgresqlIdentRule for the postgresql.identRule resource
type mqlPostgresqlIdentRule struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlIdentRuleInternal it will be used here
	LineNumber     plugin.TValue[int64]
	FileName       plugin.TValue[string]
	MapName        plugin.TValue[string]
	SystemUsername plugin.TValue[string]
	PgUsername     plugin.TValue[string]
	Error          plugin.TValue[string]
}

// createPostgresqlIdentRule creates a new instance of this resource
func createPostgresqlIdentRule(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlIdentRule{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.identRule", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlIdentRule) MqlName() string {
	return "postgresql.identRule"
}

func (c *mqlPostgresqlIdentRule) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlIdentRule) GetLineNumber() *plugin.TValue[int64] {
	return &c.LineNumber
}

func (c *mqlPostgresqlIdentRule) GetFileName() *plugin.TValue[string] {
	return &c.FileName
}

func (c *mqlPostgresqlIdentRule) GetMapName() *plugin.TValue[string] {
	return &c.MapName
}

func (c *mqlPostgresqlIdentRule) GetSystemUsername() *plugin.TValue[string] {
	return &c.SystemUsername
}

func (c *mqlPostgresqlIdentRule) GetPgUsername() *plugin.TValue[string] {
	return &c.PgUsername
}

func (c *mqlPostgresqlIdentRule) GetError() *plugin.TValue[string] {
	return &c.Error
}

// mqlPostgresqlReplicationSlot for the postgresql.replicationSlot resource
type mqlPostgresqlReplicationSlot struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlReplicationSlotInternal it will be used here
	SlotName          plugin.TValue[string]
	Plugin            plugin.TValue[string]
	SlotType          plugin.TValue[string]
	Database          plugin.TValue[string]
	Active            plugin.TValue[bool]
	ActivePid         plugin.TValue[int64]
	Temporary         plugin.TValue[bool]
	RestartLsn        plugin.TValue[string]
	ConfirmedFlushLsn plugin.TValue[string]
	WalStatus         plugin.TValue[string]
	TwoPhase          plugin.TValue[bool]
}

// createPostgresqlReplicationSlot creates a new instance of this resource
func createPostgresqlReplicationSlot(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlReplicationSlot{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.replicationSlot", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlReplicationSlot) MqlName() string {
	return "postgresql.replicationSlot"
}

func (c *mqlPostgresqlReplicationSlot) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlReplicationSlot) GetSlotName() *plugin.TValue[string] {
	return &c.SlotName
}

func (c *mqlPostgresqlReplicationSlot) GetPlugin() *plugin.TValue[string] {
	return &c.Plugin
}

func (c *mqlPostgresqlReplicationSlot) GetSlotType() *plugin.TValue[string] {
	return &c.SlotType
}

func (c *mqlPostgresqlReplicationSlot) GetDatabase() *plugin.TValue[string] {
	return &c.Database
}

func (c *mqlPostgresqlReplicationSlot) GetActive() *plugin.TValue[bool] {
	return &c.Active
}

func (c *mqlPostgresqlReplicationSlot) GetActivePid() *plugin.TValue[int64] {
	return &c.ActivePid
}

func (c *mqlPostgresqlReplicationSlot) GetTemporary() *plugin.TValue[bool] {
	return &c.Temporary
}

func (c *mqlPostgresqlReplicationSlot) GetRestartLsn() *plugin.TValue[string] {
	return &c.RestartLsn
}

func (c *mqlPostgresqlReplicationSlot) GetConfirmedFlushLsn() *plugin.TValue[string] {
	return &c.ConfirmedFlushLsn
}

func (c *mqlPostgresqlReplicationSlot) GetWalStatus() *plugin.TValue[string] {
	return &c.WalStatus
}

func (c *mqlPostgresqlReplicationSlot) GetTwoPhase() *plugin.TValue[bool] {
	return &c.TwoPhase
}

// mqlPostgresqlPublication for the postgresql.publication resource
type mqlPostgresqlPublication struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlPublicationInternal it will be used here
	Oid             plugin.TValue[int64]
	Name            plugin.TValue[string]
	Owner           plugin.TValue[string]
	AllTables       plugin.TValue[bool]
	InsertEnabled   plugin.TValue[bool]
	UpdateEnabled   plugin.TValue[bool]
	DeleteEnabled   plugin.TValue[bool]
	TruncateEnabled plugin.TValue[bool]
}

// createPostgresqlPublication creates a new instance of this resource
func createPostgresqlPublication(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlPublication{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.publication", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlPublication) MqlName() string {
	return "postgresql.publication"
}

func (c *mqlPostgresqlPublication) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlPublication) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresqlPublication) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlPublication) GetOwner() *plugin.TValue[string] {
	return &c.Owner
}

func (c *mqlPostgresqlPublication) GetAllTables() *plugin.TValue[bool] {
	return &c.AllTables
}

func (c *mqlPostgresqlPublication) GetInsertEnabled() *plugin.TValue[bool] {
	return &c.InsertEnabled
}

func (c *mqlPostgresqlPublication) GetUpdateEnabled() *plugin.TValue[bool] {
	return &c.UpdateEnabled
}

func (c *mqlPostgresqlPublication) GetDeleteEnabled() *plugin.TValue[bool] {
	return &c.DeleteEnabled
}

func (c *mqlPostgresqlPublication) GetTruncateEnabled() *plugin.TValue[bool] {
	return &c.TruncateEnabled
}

// mqlPostgresqlSubscription for the postgresql.subscription resource
type mqlPostgresqlSubscription struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlSubscriptionInternal it will be used here
	Oid               plugin.TValue[int64]
	Name              plugin.TValue[string]
	Owner             plugin.TValue[string]
	Enabled           plugin.TValue[bool]
	ConnInfo          plugin.TValue[string]
	SlotName          plugin.TValue[string]
	SynchronousCommit plugin.TValue[string]
	PublicationNames  plugin.TValue[[]any]
}

// createPostgresqlSubscription creates a new instance of this resource
func createPostgresqlSubscription(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlSubscription{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.subscription", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlSubscription) MqlName() string {
	return "postgresql.subscription"
}

func (c *mqlPostgresqlSubscription) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlSubscription) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresqlSubscription) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlSubscription) GetOwner() *plugin.TValue[string] {
	return &c.Owner
}

func (c *mqlPostgresqlSubscription) GetEnabled() *plugin.TValue[bool] {
	return &c.Enabled
}

func (c *mqlPostgresqlSubscription) GetConnInfo() *plugin.TValue[string] {
	return &c.ConnInfo
}

func (c *mqlPostgresqlSubscription) GetSlotName() *plugin.TValue[string] {
	return &c.SlotName
}

func (c *mqlPostgresqlSubscription) GetSynchronousCommit() *plugin.TValue[string] {
	return &c.SynchronousCommit
}

func (c *mqlPostgresqlSubscription) GetPublicationNames() *plugin.TValue[[]any] {
	return &c.PublicationNames
}

// mqlPostgresqlTablespace for the postgresql.tablespace resource
type mqlPostgresqlTablespace struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlTablespaceInternal it will be used here
	Oid      plugin.TValue[int64]
	Name     plugin.TValue[string]
	Owner    plugin.TValue[string]
	Location plugin.TValue[string]
}

// createPostgresqlTablespace creates a new instance of this resource
func createPostgresqlTablespace(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlTablespace{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.tablespace", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlTablespace) MqlName() string {
	return "postgresql.tablespace"
}

func (c *mqlPostgresqlTablespace) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlTablespace) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresqlTablespace) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlTablespace) GetOwner() *plugin.TValue[string] {
	return &c.Owner
}

func (c *mqlPostgresqlTablespace) GetLocation() *plugin.TValue[string] {
	return &c.Location
}

// mqlPostgresqlLanguage for the postgresql.language resource
type mqlPostgresqlLanguage struct {
	MqlRuntime *plugin.Runtime
	__id       string
	// optional: if you define mqlPostgresqlLanguageInternal it will be used here
	Oid     plugin.TValue[int64]
	Name    plugin.TValue[string]
	Owner   plugin.TValue[string]
	Trusted plugin.TValue[bool]
}

// createPostgresqlLanguage creates a new instance of this resource
func createPostgresqlLanguage(runtime *plugin.Runtime, args map[string]*llx.RawData) (plugin.Resource, error) {
	res := &mqlPostgresqlLanguage{
		MqlRuntime: runtime,
	}

	err := SetAllData(res, args)
	if err != nil {
		return res, err
	}

	if res.__id == "" {
		res.__id, err = res.id()
		if err != nil {
			return nil, err
		}
	}

	if runtime.HasRecording {
		args, err = runtime.ResourceFromRecording("postgresql.language", res.__id)
		if err != nil || args == nil {
			return res, err
		}
		return res, SetAllData(res, args)
	}

	return res, nil
}

func (c *mqlPostgresqlLanguage) MqlName() string {
	return "postgresql.language"
}

func (c *mqlPostgresqlLanguage) MqlID() string {
	return c.__id
}

func (c *mqlPostgresqlLanguage) GetOid() *plugin.TValue[int64] {
	return &c.Oid
}

func (c *mqlPostgresqlLanguage) GetName() *plugin.TValue[string] {
	return &c.Name
}

func (c *mqlPostgresqlLanguage) GetOwner() *plugin.TValue[string] {
	return &c.Owner
}

func (c *mqlPostgresqlLanguage) GetTrusted() *plugin.TValue[bool] {
	return &c.Trusted
}
